version: "3.9"

services:
  web_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development
    volumes:
      - public-data:/var/lib/mysql
    networks:
      - web
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: web_db
      WORDPRESS_DB_PASSWORD: development
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./dist:/var/www/html/wp-content/themes/dist
      - wp-content:/var/www/html/wp-content/plugins
      - wp-content:/var/www/html/wp-content/uploads
    networks:
      - web
    depends_on:
      - web_db

networks:
  web:
volumes:
  wp-content:
  public-data:
