version: '3.7'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: disruptv_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '128M');
        define('WP_DEFAULT_THEME', 'Disruptv');
    volumes:
      - ./dist:/var/www/html/wp-content/themes/disruptv
      - ./wordpress/wp-plugins:/var/www/html/wp-content/plugins
      - ./wordpress/wp-uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./wordpress/wp-data:/var/lib/mysql
